/**
 * Markdown generation and export service
 */

import type { AnalysisResult } from '@/types/mr';

export function generateMarkdown(result: AnalysisResult): string {
  const { mrDetails, diffSummary, analyzedAt } = result;

  const formattedDate = new Date(analyzedAt).toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const formattedCreatedAt = new Date(mrDetails.createdAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `# GitLab MR Analysis: ${mrDetails.title}

**Analyzed on:** ${formattedDate}
**MR URL:** ${mrDetails.url}

---

## Merge Request Details

- **Author:** ${mrDetails.author.name}
- **Source Branch:** \`${mrDetails.sourceBranch}\`
- **Target Branch:** \`${mrDetails.targetBranch}\`
- **Created:** ${formattedCreatedAt}
- **Collaborators:** ${mrDetails.collaborators.map(c => c.name).join(', ')}

---

## Summary

${diffSummary.overview}

---

## Statistics

| Metric | Value |
|--------|-------|
| Files Changed | ${diffSummary.filesChanged} |
| Additions | +${diffSummary.additions} |
| Deletions | -${diffSummary.deletions} |

---

## Key Changes

${diffSummary.keyChanges.map((change, index) =>
  `### ${index + 1}. \`${change.file}\`

${change.description}
`).join('\n')}

---

*Generated by GitLab MR Diff Summarizer*
`;
}

export function downloadMarkdown(content: string, filename: string = 'mr-analysis.md'): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}
